### ISSUE TITLE
Void mobs being removed

### ISSUE THREAD

**Issue by srnyx** [Globox1997/VoidZ#3]
I'm using a mod that removes mobs that would otherwise crash the server: https://paste.srnyx.xyz/gakivutovu.yaml

**Comment by Globox1997** [comment]
Thanks for the report, didn't test it on the server before release :)
Not enough crashes makes it a little harder to figure out the problem^^
Fixed with [https://github.com/Globox1997/AdventureZ/commit/5c662294acbcb3672d5304b348ff933fcb8772b2](https://github.com/Globox1997/AdventureZ/commit/5c662294acbcb3672d5304b348ff933fcb8772b2)
